# Installation and Configuration HAProxyHQ
----------------------------------------

## 1.Requirements

* Access to an Openstack environment
* MongoDB and RabbitMQ Service instances
* Deployed Backend
* Heatscript

## 2. Configuration

Some steps are currently executed manually:

* Creation of a RabbitMQ queue

This task will be described in the following documentation.

### 2.1 MongoDB and RabbitMQ Service instances

The HAProxyHQ needs both MongoDB and RabbitMQ. Both are provided as service instances in Cloud Foundry and are created with the following commands:

....
cf create-service MongoDB S NameOfMongoDBInstance
cf create-service RabbitMQ S NameOfRabbitMQInstance
....

The HAProxyHQ Agent requires the credentials for the RabbitMQ instance. To get these you have to get the service instances first.

....
cf curl /v2/service_instances
....

Then you have to look for the instance with property `entity.name` NameOfRabbitMQInstance. This instance has a field named `service_bindings_url` with which the connection details for RabbitMQ can be determined in the next step.

....
cf curl /v2/service_instances/1x111111-1111-11x1-111x-x11xx1111xxx/service_bindings
....

You can find the property `entity.credentials.uri` in the output, in which the user, the password, the server address, the server port and the virtual host are stored according to the following scheme:

....
amqp://user:password@server:port/virtualhost
....

This data will be needed in the following step.

### 2.2 Backend

It is important to define a token for a mutual authorization. This token has to be stored in the `application.yml` as seen below.

....
security:
    token:
        default: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        name: X-Auth-Token
....

Besides the adjustment of the `application.yml` the specific `application-<location>.yml` has to be adjusted as well, in which the exchange and routingkey are defined.

....
---
spring:
    profiles: <profile>

rabbitmq:
    routingkey:
        prefix: /haproxyhq/agents/
exchange:
    prefix: /haproxyhq/agents/

haproxy:
    port_range:
        start: <port_range_start>
        end: <port_range_end>
    external_ip: <external_ip>
....

### 2.3 RabbitMQ

The routingkey prefix+agent is mapped on a Queue on the RabbitMQ server (e.g. ``/haproxyhq/agents/
58944eca4334a03ec4f01770 –> /haproxyhq/agents/58944eca4334a03ec4f01770``). The queue's name will be entered into the agent's configuration in the next step.

### Heatscript

In the beginning an instance will be created in Openstack using the following heatscript:

....
heat_template_version: 2013-05-23
description: Deployment Description for HAProxy
parameters:
    image_id:
        type: string
        description: Image used for servers
    keypair:
        type: string
        description: SSH key to connect to the servers
    flavor:
        type: string
        description: flavor used by the web servers
    network_id:
        type: string
        description: Network used by the server
    repository_url:
        type: string
        description: URL of Agent's repository
        default: https://github.com/evoila/haproxy-agent
    repository_branch:
        type: string
        description: Branch of repository
        default: rabbitmq
    server_address:
        type: string
        description: Address of HAProxy Server
    server_port:
        type: string
        description: Port of HAProxy Server
    server_protocol:
        type: string
        description: Protocol to use e.g http
    agent_id:
        type: string
        description: ID of HAProxy Agent
    agent_token:
        type: string
        description: Token of HAProxy Agent
    rabbit_mq_host:
        type: string
        description: Adress of RabbitMQ Server
    rabbit_mq_port:
        type: string
        description: Port of RabbitMQ Server
    rabbit_mq_virtual_host:
        type: string
        description: Virtual Host of RabbitMQ Server
    rabbit_mq_username:
        type: string
        description: Username for the Virtual Host on the RabbitMQ Server
    rabbit_mq_password:
        type: string
        description: Password for the Virtual Host on the RabbitMQ Server
    rabbit_mq_queue:
        type: string
        description: Queue to be used on the RabbitMQ Server
    ha_proxy_config_path:
        type: string
        description: Path of HAProxy Config
    ha_proxy_topic_prefix:
        type: string
        description: Prefix for AMQP Topics

resources:
    nova_instance:
        type: OS::Nova::Server
    properties:
        flavor: {get_param: flavor}
        image: {get_param: image_id}
        key_name: {get_param: keypair}
        networks: [{network: {get_param: network_id} }]
        user_data_format: RAW
        security_groups:
            - default
            - cf-private
        user_data:
            str_replace:
            template: |
                    #!/bin/bash

                    apt-cache showpkg haproxy
                    add-apt-repository ppa:vbernat/haproxy-1.6 -y
                    apt-get update
                    apt-get install haproxy -y

                    cd /home/ubuntu
                    cat <<EOT >> agent.conf
                    [agent]
                    id = $agent_id
                    token = $agent_token

                    [haproxy]
                    config_file = $ha_proxy_config_path

                    [rabbitmq]
                    host = $rabbit_mq_host
                    port = $rabbit_mq_port
                    virtualhost = $rabbit_mq_virtual_host
                    username = $rabbit_mq_username
                    password = $rabbit_mq_password
                    exchange = $ha_proxy_topic_prefix$agent_id
                    queue = $rabbit_mq_queue

                    [server]
                    protocol = $
                    address = $server_address
                    port = $server_port
                    api_endpoint = agents
                    EOT

                    sudo apt-get install python-pip -
                    git clone -b $repository_branch $repository_url
                    rm /etc/haproxyhq/agent.conf
                    mkdir /etc/haproxyhq/
                    cp /home/ubuntu/agent.conf /etc/haproxyhq/
                    cd /home/ubuntu/haproxy-agent/
                    python /home/ubuntu/haproxy-agent/setup.py install
                    cd /home/ubuntu/haproxy-agent/haproxy_hq_agent
                    haproxy-agent --config-file=/etc/haproxyhq/agent.conf

        params:
                $server_address: {get_param: server_address}
                $server_port: {get_param: server_port}
                $server_protocol: {get_param: server_protocol}
                $agent_id: {get_param: agent_id}
                $agent_token: {get_param: agent_token}
                $rabbit_mq_host: {get_param: rabbit_mq_host}
                $rabbit_mq_port: {get_param: rabbit_mq_port}
                $rabbit_mq_virtual_host: {get_param: rabbit_mq_virtual_host}
                $rabbit_mq_username: {get_param: rabbit_mq_username}
                $rabbit_mq_password: {get_param: rabbit_mq_password}
                $rabbit_mq_queue: {get_param: rabbit_mq_queue}
                $ha_proxy_config_path: {get_param: ha_proxy_config_path}
                $ha_proxy_topic_prefix: {get_param: ha_proxy_topic_prefix}
                $repository_url: {get_param: repository_url}
                $repository_branch: {get_param: repository_branch}
....

With the creation of the instance you have to fill in above fields.

[width="80%",cols="20%,80%",options="header",]
|=======================================================================
|Field |Value
|image_id |ID of the used image (has to be looked up in OpenStack)

|keypair |SSH-Key for the instance access (has to be deposited in OpenStack)

|flavor |Flavor-ID e.g. gp1.small

|network_id |The network's id (has to be looked up in OpenStack)

|repository_url |URL of the HAProxy Agent's repository

|repository_branch |The used branch

|server_address |The address of the HAProxy Backend

|server_port |The port of the HAProxy Backend

|server_protocol |The used (https or http)

|agent_id |Name of the agent. Will be created automatically by the agent

|agent_token |The token of the agent (has to be identical to the token written in the `application.yml`)

|rabbit_mq_host |Host of the RabbitMQ instance (can be determined with `cf-curl`)

|rabbit_mq_port |Port of the RabbitMQ instance

|rabbit_mq_virtual_host |Virtual Host of the RabbitMQ instance

|rabbit_mq_username |Username for the RabbitMQ instance

|rabbit_mq_password |Password for the RabbitMQ instance

|rabbit_mq_queue |The used queue of the RabbitMQ instance

|ha_proxy_config_path |The path to the HAProxy's configuration file
(default: /etc/haproxy/haproxy.cfg)

|ha_proxy_topic_prefix |Used prefix (default: /agents)
|=======================================================================

### 2.4 Agent

The Agent has been configurated mostly with the creation of the instance in OpenStack. All necessary information can be found in the configuration file `agent.conf`, which looks as follows:

....
[agent]
id = <agent_id>
token = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[haproxy]
config_file = /etc/haproxy/haproxy.cfg

[rabbitmq]
host = <rabbitmq_host>
port = 5672
virtualhost = <rabbitmq_virtual_host>
username = <username>
password = <password>
exchange = /haproxyhq/agents/58944eca4334a03ec4f01770
queue = haproxy.sb

[server]
protocol = <http, https>
address = <server_address>
port = <server_port>
api_endpoint = agents
....

## 3. Usage

In the following the available REST-API will be listed.

### 3.1 Listing of connected agents

....
GET [base_url]/agents HTTP/1.1
Content-Type: application/json
....

#### 3.1.1 Description

Listing of all connected agents. Therefore the agent's name, IP and timestamp of the current configuration file and of the last heartbeat will be returned amongst other things.

#### 3.1.2 Parameters

[cols=",,,",options="header",]
|=======================================================================
|Type |Name |Description |Required
|Header |X-Auth-Token |Authorrization Token between backend and agent
|true
|=======================================================================

#### 3.1.3 Responses

[cols=",,",options="header",]
|==============================
|HTTP Code |Description |Schema
|200 |OK |null
|==============================

### 3.2 Creation of an agent in the backend

....
POST [base_url]/agents HTTP/1.1
Content-Type: application/json
....

#### 3.2.1

Creation of an agent in the backend. With the generated ID the agent can be configured to communicate with the backend.

#### 3.2.2 Parameters

[cols=",,,",options="header",]
|=======================================================================
|Type |Name |Description |Required
|Header |X-Auth-Token |Authorrization Token between backend and agent
|true

|Body |name |Name that should be assigned to the agent |true

|Body |description |Description of the agent |true

|Body |ip |Public Ip of the agent |true

|Body |authToken |Used X-Auth-Token |true
|=======================================================================

#### 3.2.3 Responses

[cols=",,",options="header",]
|==============================
|HTTP Code |Description |Schema
|200 |OK |
|==============================

### 3.3 Query of the current configuration of an agent

....
GET [base_url]/agents|[agent_id] HTTP/1.1
Content-Type: application/json
....

#### 3.3.1 Description

Query of the configuration, that is currently assigned to an agent. You will receive a timestamp and the date of the configuration file. Additionally the file's content will be listed.

#### 3.3.2 Parameters

[cols=",,,",options="header",]
|=======================================================================
|Type |Name |Description |Required
|Header |X-Auth-Token |Authorization Token between backend and agent
|true

|Path |agent_id |The id of the agent |true
|=======================================================================

#### 3.3.3 Responses

[cols=",,",options="header",]
|==============================
|HTTP Code |Description |Schema
|200 |OK |
|==============================

### 3.4 Addition of a host to the configuration file of a HAProxy

....
PUT [base_url]/agents/[agent_id] HTTP/1.1
Content-Type: application/json
....

#### 3.4.1 Description

Addition of a host to the configuration file of a HAProxy with the agent. After the call the host with the given port should be accessible with the agent's public IP and the port mentioned in the response.

#### 3.4.2 Parameters

[width="100%",cols="25%,25%,25%,25%",options="header",]
|=======================================================================
|Type |Name |Description |Required
|Header |X-Auth-Token |Authorization Token between backend and agent
|true

|URL |agent_id |The id of the agent |true

|Body |name |Name thatshould be assigned to the agent |true

|Body |ip |Private ip address of the service that should be provided |true

|Body |port |Port of the service that should be provided |true
|=======================================================================

#### 3.4.3 Responses

[cols=",,",options="header",]
|==============================
|HTTP Code |Description |Schema
|200 |OK |null
|==============================

### 3.5 Erasure of a listener section

....
DELETE [base_url]/agents/[agent_id]/schemas/[type]
Content-Type: application/json
....

#### 3.5.1 Description

Erasure of a listener section from the HAProxy config.

#### 3.5.2 Parameters

[cols=",,,",options="header",]
|=======================================================================
|Type |Name |Description |Required
|Header |X-Auth-Token |Authorization Token between backend and agent
|true

|Body |ip |IP of the section |true
|Body |port |Port of the section | true
|Path |agent_id |ID of the agent |true
|URL |type |Type of the section (e.g. listener) |true
|=======================================================================

#### 3.5.3 Responses

[cols=",,",options="header",]
|==============================
|HTTP Code |Description |Schema
|200 |OK |null
|==============================