spring:
  application:
    name: haproxy-backend

haproxy:  
  port_range:
    start: 5000
    end: 7500
  
security:
  token: 
    default: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    name: X-Auth-Token
---  
spring:
  profiles: default,development
server:
  port: 8080
  
database:
  nosql:
    host: 88.198.249.61
    user: 27807a83-2017-41ea-a426-5673d62c4446
    password: uie4o53595oal25llkvbjig019
    port: 7777
    database: 06ed3c55-a674-474a-94a7-86c84abcd3f2

mqtt:
  host: tcp://88.198.249.61:1883
  client:
    id: haproxyhq/backend
  topic:
    prefix: /haproxyhq/agents/

haproxy:
  external_ip: 88.198.249.61

---
spring:
  profiles: lab


spring:
  rabbitmq:
    host: 
    port:

mqtt:
  host: tcp://172.24.100.35:1883
  client:
    id: haproxyhq/backend
  topic:
    prefix: /haproxyhq/agents/

haproxy:
  external_ip: 88.198.249.61

---
spring: 
  profiles: cloud

server:
  port: 0

  